### ISSUE TITLE
Qualisys node crashes on Ubuntu 16.04 due to Eigen alignment issue

### ISSUE THREAD

**Issue by kartikmohta** [KumarRobotics/motion_capture_system#7]

**Comment by mike-watterson-ai** [comment]
0a512f712dc4cda97b7266d40d6950533c4a5e75 and 3e56a6ffc81beaee489c08cee779feafab727177

I have tested this with the Vicon system but not the Qualisys.

**Comment by kartikmohta** [comment]
Let's assume this is fixed 🙂
